### ISSUE TITLE
Error in regex: end pattern with unmatched parenthesis

### ISSUE THREAD

**Issue by harli91** [fator7/OpenEdge-ABL#10]
![image](https://cloud.githubusercontent.com/assets/3657605/10966761/738d3118-83be-11e5-810b-1b788253ecf6.png)

**Comment by harli91** [comment]
(exclusive)-lock shoul be (exclusive-lock)

**Comment by taschetto** [comment]
It has already been fixed. Please update the package. Sorry for that. :)
