### ISSUE TITLE
Sublime's suport for ibm850 char encoding

### ISSUE THREAD

**Issue by SparK-Cruz** [fator7/OpenEdge-ABL#4]
People outside USA won't benefit from the extension if we can't write with the proper encoding, lot's of special symbols get scrambled when displayed in AppBuilder.
Is there any way to add ibm850 encoding to sublime as part of the package, if NO then nevermind my request...

**Comment by taschetto** [comment]
I believe encoding support is a Sublime feature. Therefore, there's nothing we can do here. But we use Sublime for ABL programming here too. We set Sublime to work with `Western (Windows 1252` encoding and it works like a charm. Give it a try!

Let us know if you have further issues. :)
